feat: RBTC - BTCS bridge (WIP)
DistributedCollective/bridge-dapp pull request #115
Opened 2022-02-18 12:12 UTC by creed-victor

2022-03-01 15:29 UTC, tiltom requested changes

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/DestinationChainCard/index.tsx
> +                placeholder="Enter or paste address"
```suggestion
                placeholder="Enter or paste an address"
```

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/DestinationChainCard/index.tsx
> +                : '+ Click here to receive at external address'}
```suggestion
                ? '- Click here to receive at the current address'
                : '+ Click here to receive at an external address'}
```

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/TransactionDialog/components/StepConfirm.tsx
> +import React from 'react';
This is the same component as `StepApprove`, delete one of them and create an interface that will have an enum (e.g. `Step` with values `Approve` and `Confirm`).

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/TransactionDialog/components/StepMain.tsx
> +  </>
```suggestion
    <Spinner size={96} />
```

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/TransactionDialog/components/StepPending.tsx
> +import React from 'react';
This is the same component as `StepConfirmed`, delete one of them and unify them.

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/TransactionDialog/components/WalletLogo.tsx
> +  return (
```suggestion
export const WalletLogo: React.FC<IWalletLogoProps> = ({ wallet }) => (
```

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/TransactionDialog/utils.ts
> +export const getWalletName = walletName => {
Rewrite to `switch`.

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/components/TransactionDialog/utils.ts
> +export const getWalletImage = walletName => {
Rewrite to `switch`.

2022-03-01 15:29 UTC, tiltom commented on src/app/containers/BridgePage/saga.ts
> +        let basset = (
```suggestion
        let bAsset = (
```

2022-03-01 15:29 UTC, tiltom commented on src/styles/tailwindcss/components/dialog.css
> +        margin-bottom: 40px;
```suggestion
        @apply font-semibold text-center mx-auto mb-10;
```

2022-03-01 15:29 UTC, tiltom commented on src/styles/tailwindcss/components/dialog.css
>          @apply w-full;
```suggestion
        @apply bg-black text-white w-full relative tracking-normal;
```

2022-03-01 15:29 UTC, tiltom commented on src/styles/tailwindcss/components/dialog.css
>          letter-spacing: 0;
```suggestion
```

2022-03-01 15:29 UTC, tiltom commented on src/utils/helpers.ts
> +export function detectWeb3Wallet() {
```suggestion
export const detectWeb3Wallet = () => {
```

2022-03-02 14:12 UTC, creed-victor commented
Spec changed so will continue working on this, but i think current files can be reviewed

2022-03-14 12:18 UTC, ShynRou requested changes
Testing rBTC to BTCS with one of my test addresses (0x653c65d44D062344A35a0204f94C1D0a59b54a25) leads to this error:
![image](https://user-images.githubusercontent.com/20092263/158169509-368ff66b-1de4-4da5-a077-416de4547103.png)
While using another the transfer worked, except that the bridge does not display the BTCS balance (on bscscan I can see that I received the tokens).

2022-03-16 12:13 UTC, creed-victor commented
> Testing rBTC to BTCS with one of my test addresses (0x653c65d44D062344A35a0204f94C1D0a59b54a25) leads to this error: ![image](https://user-images.githubusercontent.com/20092263/158169509-368ff66b-1de4-4da5-a077-416de4547103.png) While using another the transfer worked, except that the bridge does not display the BTCS balance (on bscscan I can see that I received the tokens).

@ShynRou, it always throws error for this address but not for other one?

2022-04-07 12:03 UTC, Alitasovryn commented
<img width="1409" alt="Screen Shot 2022-04-07 at 8 02 18 AM" src="https://user-images.githubusercontent.com/94629682/162194295-610070fd-c21e-4c0e-b885-c7bacc5b14aa.png">
<img width="1412" alt="Screen Shot 2022-04-07 at 8 00 56 AM" src="https://user-images.githubusercontent.com/94629682/162194318-544bdf58-c432-4691-8f07-1bf17ac9e314.png">

Working fine

2022-04-07 12:03 UTC, Alitasovryn approved these changes

2022-04-07 12:05 UTC, JoeStorm99 approved these changes

2022-04-08 12:10 UTC, merged