BTCS bridge
DistributedCollective/bridge-dapp pull request #117
Opened 2022-04-28 09:14 UTC by creed-victor

2022-05-03 13:59 UTC, tiltom requested changes

2022-05-03 13:59 UTC, tiltom commented on src/services/interactions/babelfish.ts
> +    mAssetQuanity: string,
```suggestion
    mAssetQuantity: string,
```

2022-05-05 07:30 UTC, tiltom approved these changes

2022-05-12 10:40 UTC, ShynRou commented on src/dictionaries/assets/bsc-rsk-testnet-assets.ts
> +    '0x0ed2a1edde92b25448db95e5aa9fe9e9bc0193bf',
Shouldn't this be the latest testnet BTCS token address?
```suggestion
    '0xb68faC988f5aD33044f998F363a1ECe08FD047D6',
```

2022-06-16 10:22 UTC, merged